---
label: Project
hide_body: true
display_field: title
fields:
- name: date
  type: datetime
  label: Date
  description: Date this project was created
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: title
  type: text
  config:
    required: false
  label: Title
  description: Enter your project title.
  default: New Project
- name: color
  type: color
  label: Background Color
  config:
    required: false
    color_format: Hex
  description: Set a background color for your project.
- name: project_line_color
  type: color
  label: Line Color
  config:
    required: false
    color_format: Hex
  default: "#9879B0"
  description: Set a color for the horizontal at top of project page.
- name: text_color
  type: color
  label: Text Color
  config:
    required: false
    color_format: Hex
  default: "#000000"
  description: Set the color for the text on your project page.
- name: categories
  type: list
  config:
    use_select: true
    min: 1
    max: 
    source:
      type: documents
      section: ''
      file: content/site/site.json
      path: category_tags
  label: Categories
  description: Assign categories to your project page. <strong><em>Note:</em></strong><em>
    list of available tags pulls from Category Tags field in the Index section.</em>
- name: image_gallery
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 1
    label: Image
    description: Upload your image here
  - name: caption
    type: textarea
    default: New image caption
    config:
      required: false
      wysiwyg: true
      schema:
        format: html
    label: Caption
    description: Enter image caption here.
  - name: featured_image
    type: boolean
    label: Featured Image
    description: This is the image that will appear when the user hovers over the
      project title on the home page.
  config:
    min: 
    max: 
    labelField: 
  label: Image Gallery
  description: Enter your image and captions here.
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: Description
  description: Enter your project description here.
pages:
- content/projects/atlas-rock-center.md
- content/projects/bon-appetit-hot-10-2018.md
- content/projects/bon-appetit-hot-10-2019.md
- content/projects/bon-appetit-special-issue.md
- content/projects/d-addario-built-to-compete.md
- content/projects/peden-munk.md
- content/projects/test.md
