---
label: Site Settings
hide_body: true
fields:
- type: textarea
  name: bio
  label: Bio
  description: This is the part where you write about yourself.
  config:
    wysiwyg: true
    schema:
      format: html
- name: index_color
  type: color
  config:
    required: false
    color_format: Hex
  description: Set a custom background color for index page.
  default: "#FFD0D0"
  label: Index Background Color
- name: index_line_color
  type: color
  label: Line Color
  config:
    required: false
    color_format: Hex
  default: "#9879B0"
- name: index_text_color
  type: color
  label: Index Text Color
  config:
    required: false
    color_format: Hex
  description: Set the text color for text on the index page.
  default: "#000000"
- name: mobile_menu_background_color
  type: color
  label: Mobile Menu Background Color
  config:
    required: false
    color_format: Hex
  description: This sets the background color for the mobile menu.
  default: "#FFFAF0"
- name: category_tags
  type: tag_list
  default: []
  label: Category Tags
- name: category_color
  type: field_group_list
  fields:
  - name: select_category
    type: select
    default: ''
    config:
      required: false
      options: []
      source:
        type: documents
        section: site-settings
        file: content/site/site.json
        path: category_tags
    label: Select Category
  - name: tag_color
    type: color
    label: Tag Color
    config:
      required: false
      color_format: Hex
  config:
    min: 
    max: 
    labelField: select_category
  label: Category Color
  description: Assign a color to each category
pages:
- content/site/site.json
